### ISSUE TITLE
RBAC with domains and explicit user policy

### ISSUE THREAD

**Issue by wiphi** [casbin4d/Casbin4D#20]
Hi folks,
I think there is a bug in the RBAC implementation. 

Please consider the following model
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

with the following policy-file:

```csv
p, admin, domain1, data1, read
p, admin, domain1, data1, write
p, admin, domain2, data2, read
p, admin, domain2, data2, write

p, alice, domain3, data3, read

g, alice, admin, domain1
g, bob, admin, domain2
```

If you test the follow request `alice, domain3, data3, read` or `admin, domain1, data1, read` in the casbon online editor (https://casbin.org/editor/) the enforcment result will be always `true`. 

If you test this in the Casbin4D Demo, the result is always `false`. I think this is a bug, because you can have role permissions with explicit user policies in addition.

I debugged this a while, but I don't find any simple solution for that. I think we need a link to the role / user itself, or a better `linkExists`-logic in the policy. What did you think?

Best regards.

**Comment by hsluoyz** [comment]
@jkour

**Comment by jkour** [comment]
@wiphi 

@hsluoyz, do you think `alice, domain3, data3, read` should resolve to `true`?

`alice` does not belong to any `g`s with access to `domain3` and `g(r.sub, p.sub, r.dom)` resolves to false

**Comment by wiphi** [comment]
> @wiphi
> 
> @hsluoyz, do you think `alice, domain3, data3, read` should resolve to `true`?
> 
> `alice` does not belong to any `g`s with access to `domain3` and `g(r.sub, p.sub, r.dom)` resolves to false

I think so, because when I resolve this I get:
`g(r.alice, p.alice, r.domain3)`
Casbin handles all as String and don't care about users and groups (written in the docs). So `alice` is a user and a group by definition and this policy exists. So the group `g` definition will return `true`.

**Comment by hsluoyz** [comment]
@jkour @wiphi plz refer to Go Casbin for enforcement result

**Comment by jkour** [comment]
> > @wiphi
> > @hsluoyz, do you think `alice, domain3, data3, read` should resolve to `true`?
> > `alice` does not belong to any `g`s with access to `domain3` and `g(r.sub, p.sub, r.dom)` resolves to false
> 
> I think so, because when I resolve this I get: `g(r.alice, p.alice, r.domain3)` Casbin handles all as String and don't care about users and groups (written in the docs). So `alice` is a user and a group by definition and this policy exists. So the group `g` definition will return `true`.

@wiphi I am pretty sure that the `g` function resolves to false but I think because the effector is `some`, the `enforcer` should resolve to `true`.

I will have a look at it a bit later and see what is going on

**Comment by jkour** [comment]
Hi @wiphi, 

I looked at the code again and I really think that with **the matcher you have** and the policy file, `alice, domain3, data3, read` should not resolve to `true`.

The `&&` in the matcher forces the result to `false`.

if you want to give direct permission to r.sub, try this matcher:

`m = (g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act) or ((r.sub == p.sub) and r.dom = p.dom and r.obj = p.obj and r.act=p.act)`

@hsluoyz **Please, check this one. I think your code in Go doesn't behave correctly**

Now, `admin, domain1, data1, read` resolves to `false`  even with the new matcher. Again, I think this is the correct result. Although casbin treats all elements in the model as strings, the implementation of RBAC gives precedence to the role hierarchy rather than individual entities. That is, the `g`s determine the result. 

In every implementation of RBAC, you do not have free users but every user is attached to a group (e.g., admin).

Now, because casbin does not differentiate the entities (the `strings` thing) and because of the `g`s, a request with `admin` as the subject makes the enforcer to stop at the role level and return false.

To resolve this problem, add this line `g, admin, admin, domain1`.

What do you think?

**Comment by jkour** [comment]
Hi again,

I posted an update with your example. See the change log

Thanks

**Comment by wiphi** [comment]
Hi @jkour,
I was some days off. I will try it later.

Thanks for your investigation!

**Comment by wiphi** [comment]
sorry for the late reply. 
Thank you for you example. I solved the problem differently. We can close this issue.
